name: My first action

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        
        steps:
        - uses: action/checkout@v2
        - name: Install Python 3.8
          uses: actions/setup-python@v2
          with:
              python-version: 3.8
        - name: run test.py
          run: python test.py
    job_1: 
        name: File editing
        runs-on: window-latest
        steps:
          - run: value='cat cal.txt'
                 expr if ((%value>9)) %value -8 > cal.txt
                      else %value +2 > cal.txt
            shell: bash
          - name: Upload value 
            uses: actions/upload-artifact@v1
            with:
               path: cal.txt
           
                
          
           
          
