name: My first action

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Python 3.8
      run: python -m pip install --upgrade pip
    - name: run test.py
      run: python test.py
  job_1:
    name: File editing
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          value=$(<cal.txt)
          if [ $value -gt 9 ]; then
            echo $((value - 8))  > cal.txt
          else
            echo $((value + 2)) > cal.txt
          fi
      - name: Upload value
        uses: actions/upload-artifact@v1
        with:
          name: edited-file
          path: cal.txt
