name: My first action

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        
        steps:
        - uses: action/checkout@v3
        - name: Install Python 3.8
          run: python -m pip install --upgrade pip
               pip install ruff pytest
        - name: run test.py
          run: pytest test.py
    job_1: 
        name: File editing
        runs-on: windows-latest
        steps:
          - run: |
              if ( ${{ steps.build.outputs.return-code }} -gt 9 ); then
                echo $(( ${{ steps.build.outputs.return-code }} - 8 )) > cal.txt
              else
                echo $(( ${{ steps.build.outputs.return-code }} +2 )) > cal.txt
              fi
          - name: Upload value 
            uses: actions/upload-artifact@v1
            with:
               name: edited-file
               path: cal.txt
