name: My first action

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        
        steps:
        - uses: action/checkout@v2
        - name: Install Python 3.8
          uses: actions/setup-python@v2
          with:
              python-version: 3.8
        - name: run test.py
          run: python test.py
    job_1: 
        name: File editing
        runs-on: windows-latest
        steps:
          - run: |
              if [ ${{ steps.build.outputs.return-code }} -gt 9 ]; then
                echo $(( ${{ steps.build.outputs.return-code }} - 8 )) > cal.txt
              else
                echo $(( ${{ steps.build.outputs.return-code }} +2 )) > cal.txt
              fi
          - name: Upload value 
            uses: actions/upload-artifact@v1
            with:
               name: edited-file
               path: cal.txt
